"""add evidence relationship to sources

Revision ID: 4ad79588048c
Revises: bcefbf11182e
Create Date: 2026-10-01 16:32:46.464660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad79588048c'
down_revision: Union[str, Sequence[str], None] = 'bcefbf11182e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('source_relationship', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'source_relationship')
    op.drop_column('sources', 'evidence')
    # ### end Alembic commands ###
